name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Log in to Docker Hub
      uses: docker/login-action@34b7d700-3323-4221-be82-d773b601e414
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: v0.7.0
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: src/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/angular_adder_api:latest